# Copyright (c) 2018 Red Hat, Inc.
# This program and the accompanying materials are made
# available under the terms of the Eclipse Public License 2.0
# which is available at https://www.eclipse.org/legal/epl-2.0/
#
# SPDX-License-Identifier: EPL-2.0

# Use upstream image
FROM ${BUILD_ORGANIZATION}/${BUILD_PREFIX}-theia-dev:${BUILD_TAG}

${INCLUDE:instructions/github-token.env}
${INCLUDE:instructions/clone-theia.run}
# patch electron module by removing native keymap module (no need to have some X11 libraries)
RUN line_to_delete=$(grep -n native-keymap theia/dev-packages/electron/package.json | cut -d ":" -f 1) && \
    sed -i -e "${line_to_delete},1d" theia/dev-packages/electron/package.json

${INCLUDE:instructions/build-theia.run}
