# Copyright (c) 2018-2019 Red Hat, Inc.
# This program and the accompanying materials are made
# available under the terms of the Eclipse Public License 2.0
# which is available at https://www.eclipse.org/legal/epl-2.0/
#
# SPDX-License-Identifier: EPL-2.0
#
# Contributors:
#   Red Hat, Inc. - initial API and implementation

###
# Builder Image
#
FROM registry.access.redhat.com/ubi8/nodejs-10 as runtime

COPY build-scripts/generic/* /build/
COPY build-scripts/${BUILD_IMAGE_TARGET}/* /build/
USER root

RUN /build/01-install-dependencies.sh

${INCLUDE:instructions/build.env}
${INCLUDE:instructions/copy-generator.run}
${INCLUDE:instructions/define-home.workdir}
${INCLUDE:instructions/set.expose}
${INCLUDE:instructions/extra.env}

# Configure npm and yarn to use home folder for global dependencies
RUN /build/02-configure-npm.sh

${INCLUDE:instructions/define-projects.workdir}
${INCLUDE:instructions/define.entrypoint}

