#!/usr/bin/env node
/*********************************************************************
* Copyright (c) 2018 Red Hat, Inc.
*
* This program and the accompanying materials are made
* available under the terms of the Eclipse Public License 2.0
* which is available at https://www.eclipse.org/legal/epl-2.0/
*
* SPDX-License-Identifier: EPL-2.0
**********************************************************************/
const fs = require('fs');
const path = require('path');
const spawnSync = require('child_process').spawnSync;

const currentDir = __dirname;
const targetDir = `${__dirname}/../production/plugins`

mkdirSyncRecursive(targetDir);

fs.readdirSync(currentDir).forEach((pluginEntryName) => {
    console.log(`\n✍️  Process plugin ${pluginEntryName}`);
    
    const pluginEntryPath = `${currentDir}/${pluginEntryName}`;

    if (fs.existsSync(`${pluginEntryPath}/package.json`)) {
        console.log(`\n✍️  Running \`yarn\` on ${pluginEntryPath}`);

        const r = spawnSync('yarn', [], {
            cwd: `${pluginEntryPath}`,
            detached: true,
            stdio: "inherit"
        });

        if (r.status === 1) {
            process.exit(1);
        }
        
        fs.readdirSync(`${pluginEntryPath}`).forEach((fileName) => {
            if(fileName.endsWith('.theia')){
                console.log(`\n✍️  Copying ${pluginEntryPath}/${fileName} theia package to ${targetDir}/${fileName}`);
                fs.copyFileSync(`${pluginEntryPath}/${fileName}`, `${targetDir}/${fileName}`);
            }
        })
    } else if (pluginEntryName.endsWith('.vsix') || pluginEntryName.endsWith('.tar.gz')) {
        console.log(`\n✍️  Copying ${pluginEntryPath} VSCode built-in extension to ${targetDir}/${pluginEntryName}`);
        fs.copyFileSync(`${pluginEntryPath}`, `${targetDir}/${pluginEntryName}`);
    } else if (fs.existsSync(`${pluginEntryPath}/extension.vsixmanifest`)) {
        console.log(`\n✍️  Copying ${pluginEntryPath} VSCode built-in unpacked extension to ${targetDir}/${pluginEntryName}`);
        copyFolderSync(`${pluginEntryPath}`, `${targetDir}/${pluginEntryName}`);
    }
});

function mkdirSyncRecursive(dir) {
    const pathNodes = dir.split('/');
    for (var i = 1; i <= pathNodes.length; i++) {
        var curPath = pathNodes.slice(0, i).join('/');
        curPath.length > 0 && !fs.existsSync(curPath) ? fs.mkdirSync(curPath) : null;
    }
};

function copyFolderSync(from, to) {	
    fs.mkdirSync(to);	
    fs.readdirSync(from).forEach(element => {	
        if (fs.lstatSync(path.join(from, element)).isFile()) {	
            fs.copyFileSync(path.join(from, element), path.join(to, element));	
        } else {	
            copyFolderSync(path.join(from, element), path.join(to, element));	
        }	
    });	
}
