#!/usr/bin/env node
/*********************************************************************
* Copyright (c) 2022 Red Hat, Inc.
*
* This program and the accompanying materials are made
* available under the terms of the Eclipse Public License 2.0
* which is available at https://www.eclipse.org/legal/epl-2.0/
*
* SPDX-License-Identifier: EPL-2.0
**********************************************************************/
const fs = require('fs');
const decompress = require('decompress');
const pluginsDir = `${__dirname}/../production/plugins`;

fs.readdirSync(`${pluginsDir}`).forEach(async (pluginEntry) => {
    if (pluginEntry.endsWith('.theia')) {
        console.log(`\n✍️  Trying to decompress ${pluginEntry} package to ${pluginsDir}/${pluginEntry}`);

        const unpackedPluginFolderName = pluginEntry.substring(0, pluginEntry.lastIndexOf('.theia'));
        const decompressPromise = decompress(`${pluginsDir}/${pluginEntry}`, `${pluginsDir}/${unpackedPluginFolderName}`);

        decompressPromise.then(() => {
            console.log(`\n✍️  Removing ${pluginsDir}/${pluginEntry} after decompressing`);
            fs.unlink(`${pluginsDir}/${pluginEntry}`, () => { });
        }, error => {
            console.error(`\n✍️  Decompressing ${pluginEntry} package to ${pluginsDir}/${pluginEntry} failed: `, error);
        });
    }
});
